from __future__ import annotations

from collections.abc import Mapping, Sequence

import torch
from torch.utils.data import Dataset


class MultiScaleFrequencyTargetTransform:
    """
    Build cumulative scale targets and band residual targets from a real image.

    The readout plane is assumed to be the detector plane. For `num_levels = N`,
    this transform returns:
    - `target_scale_1 ... target_scale_N`
    - `target_band_1 ... target_band_N`
    - `target_final`

    The first `N-1` cumulative scales are generated by smooth radial low-pass
    masks with linearly spaced cutoffs. The last cumulative scale is the full
    target image itself, so `target_scale_N == target_final`.
    """

    def __init__(
        self,
        *,
        num_levels: int,
        max_freq_fraction: float = 1.0,
        transition_width: float = 0.05,
    ) -> None:
        if int(num_levels) <= 0:
            raise ValueError(f"num_levels must be positive, got {num_levels!r}")
        if not (0.0 < float(max_freq_fraction) <= 1.0):
            raise ValueError(
                f"max_freq_fraction must be in (0, 1], got {max_freq_fraction!r}"
            )
        if float(transition_width) <= 0.0:
            raise ValueError(f"transition_width must be positive, got {transition_width!r}")

        self.num_levels = int(num_levels)
        self.max_freq_fraction = float(max_freq_fraction)
        self.transition_width = float(transition_width)

    @staticmethod
    def _normalize_image(image: torch.Tensor) -> torch.Tensor:
        if image.dim() == 2:
            image = image.unsqueeze(0)
        if image.dim() != 3:
            raise ValueError(f"image must be [H,W] or [C,H,W], got {tuple(image.shape)}")
        return image.to(dtype=torch.float32)

    @staticmethod
    def _build_normalized_radius(height: int, width: int, device: torch.device, dtype: torch.dtype) -> torch.Tensor:
        fy = torch.fft.fftfreq(height, d=1.0, device=device, dtype=dtype)
        fx = torch.fft.fftfreq(width, d=1.0, device=device, dtype=dtype)
        grid_y, grid_x = torch.meshgrid(fy, fx, indexing="ij")
        radius = torch.sqrt(grid_x.square() + grid_y.square())
        radius = torch.fft.fftshift(radius)
        radius_max = torch.clamp_min(radius.max(), 1.0e-12)
        return radius / radius_max

    def _build_cumulative_scales(self, image: torch.Tensor) -> list[torch.Tensor]:
        if self.num_levels == 1:
            return [image]

        channels, height, width = image.shape
        del channels
        radius = self._build_normalized_radius(height, width, image.device, image.dtype)
        image_spectrum = torch.fft.fftshift(torch.fft.fft2(image, dim=(-2, -1), norm="ortho"), dim=(-2, -1))

        cumulative_scales: list[torch.Tensor] = []
        cutoffs = torch.linspace(
            self.max_freq_fraction / float(self.num_levels),
            self.max_freq_fraction * float(self.num_levels - 1) / float(self.num_levels),
            steps=self.num_levels - 1,
            device=image.device,
            dtype=image.dtype,
        )
        for cutoff in cutoffs:
            mask = torch.sigmoid((cutoff - radius) / self.transition_width)
            filtered = torch.fft.ifft2(
                torch.fft.ifftshift(image_spectrum * mask.unsqueeze(0), dim=(-2, -1)),
                dim=(-2, -1),
                norm="ortho",
            ).real
            cumulative_scales.append(filtered)

        cumulative_scales.append(image)
        return cumulative_scales

    def __call__(self, image: torch.Tensor) -> dict[str, torch.Tensor | tuple[torch.Tensor, ...]]:
        normalized_image = self._normalize_image(image)
        cumulative_scales = self._build_cumulative_scales(normalized_image)

        band_targets: list[torch.Tensor] = []
        previous_scale = torch.zeros_like(normalized_image)
        for scale_target in cumulative_scales:
            band_targets.append(scale_target - previous_scale)
            previous_scale = scale_target

        output: dict[str, torch.Tensor | tuple[torch.Tensor, ...]] = {
            "target_final": normalized_image,
            "target_scales": tuple(cumulative_scales),
            "target_bands": tuple(band_targets),
        }
        for level_idx, scale_target in enumerate(cumulative_scales, start=1):
            output[f"target_scale_{level_idx}"] = scale_target
        for level_idx, band_target in enumerate(band_targets, start=1):
            output[f"target_band_{level_idx}"] = band_target
        return output


class FrequencyPathDataset(Dataset):
    """Wrap a base dataset and attach multi-scale frequency targets."""

    def __init__(
        self,
        base_dataset: Dataset,
        target_transform: MultiScaleFrequencyTargetTransform,
        *,
        image_key: str = "image",
        label_key: str = "label",
        image_index: int = 0,
        label_index: int = 1,
    ) -> None:
        self.base_dataset = base_dataset
        self.target_transform = target_transform
        self.image_key = str(image_key)
        self.label_key = str(label_key)
        self.image_index = int(image_index)
        self.label_index = int(label_index)

    def __len__(self) -> int:
        return len(self.base_dataset)

    def _normalize_base_sample(self, sample: object) -> dict[str, object]:
        if isinstance(sample, Mapping):
            if self.image_key not in sample:
                raise KeyError(
                    f"base sample dict does not contain image_key={self.image_key!r}: "
                    f"keys={sorted(str(key) for key in sample.keys())}"
                )
            output = dict(sample)
            output["input"] = sample[self.image_key]
            return output

        if isinstance(sample, Sequence) and not isinstance(sample, (str, bytes)):
            if len(sample) <= self.image_index:
                raise IndexError(
                    f"base sample sequence has length {len(sample)}, missing image_index={self.image_index}"
                )
            output = {"input": sample[self.image_index]}
            if len(sample) > self.label_index:
                output[self.label_key] = sample[self.label_index]
            return output

        raise TypeError(
            "base dataset sample must be a mapping or a sequence, "
            f"got {type(sample).__name__}"
        )

    def __getitem__(self, index: int) -> dict[str, object]:
        normalized = self._normalize_base_sample(self.base_dataset[index])
        image = normalized["input"]
        if not isinstance(image, torch.Tensor):
            image = torch.as_tensor(image)
            normalized["input"] = image

        transformed_targets = self.target_transform(image)
        normalized.update(transformed_targets)
        return normalized
